force-app/main/default/objects/Kiva_Client__c/Kiva_Client__c.object-meta.xml
<CustomObject>
    <label>Kiva Client</label>
    <nameField>
        <label>Kiva Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kiva Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kiva_Client__c/fields/Client_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_First_Name__c</fullName>
    <label>Client First Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Client__c/fields/Client_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Last_Name__c</fullName>
    <label>Client Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Client__c/fields/Client_Phone__c.field-meta.xml
<CustomField>
    <fullName>Client_Phone__c</fullName>
    <label>Client Phone #</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Client__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Decline to Respond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kiva_Client__c/fields/Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status__c</fullName>
    <label>Loan Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Journal__c/Kiva_Journal__c.object-meta.xml
<CustomObject>
    <description>It is required to for each funded loan to have at least one journal entry
Information for a new journal is sent from MIS to PA2 via the API</description>
    <label>Kiva Journal</label>
    <nameField>
        <displayFormat>KJ-{000000}</displayFormat>
        <label>Kiva Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kiva Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kiva_Journal__c/fields/Kiva_Loan__c.field-meta.xml
<CustomField>
    <fullName>Kiva_Loan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This journal entry is under this Kiva loan record</description>
    <label>Kiva Loan</label>
    <referenceTo>Kiva_Loan__c</referenceTo>
    <relationshipLabel>Kiva Journals</relationshipLabel>
    <relationshipName>Kiva_Journals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/Kiva_Loan__c.object-meta.xml
<CustomObject>
    <label>Kiva Loan</label>
    <nameField>
        <displayFormat>KL-{0000000}</displayFormat>
        <label>Kiva Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kiva Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kiva_Loan__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture,120</fullName>
            </value>
            <value>
                <fullName>Animal Sales,110</fullName>
            </value>
            <value>
                <fullName>Aquaculture,218</fullName>
            </value>
            <value>
                <fullName>Beekeeping,217</fullName>
            </value>
            <value>
                <fullName>Cattle,56</fullName>
            </value>
            <value>
                <fullName>Dairy,61</fullName>
            </value>
            <value>
                <fullName>Farm Supplies,68</fullName>
            </value>
            <value>
                <fullName>Farming,31</fullName>
            </value>
            <value>
                <fullName>Flowers,177</fullName>
            </value>
            <value>
                <fullName>Land Rental,11</fullName>
            </value>
            <value>
                <fullName>Livestock,73</fullName>
            </value>
            <value>
                <fullName>Pigs,99</fullName>
            </value>
            <value>
                <fullName>Poultry,102</fullName>
            </value>
            <value>
                <fullName>Veterinary Sales,13</fullName>
            </value>
            <value>
                <fullName>Motorcycle Transport,37</fullName>
            </value>
            <value>
                <fullName>Rickshaw,156</fullName>
            </value>
            <value>
                <fullName>Taxi,59</fullName>
            </value>
            <value>
                <fullName>Transportation,107</fullName>
            </value>
            <value>
                <fullName>Adult Care,207</fullName>
            </value>
            <value>
                <fullName>Air Conditioning,105</fullName>
            </value>
            <value>
                <fullName>Auto Repair,92</fullName>
            </value>
            <value>
                <fullName>Barber Shop,28</fullName>
            </value>
            <value>
                <fullName>Beauty Salon,49</fullName>
            </value>
            <value>
                <fullName>Bicycle Repair,21</fullName>
            </value>
            <value>
                <fullName>Bookbinding,159</fullName>
            </value>
            <value>
                <fullName>Call Center,157</fullName>
            </value>
            <value>
                <fullName>Child Care,129</fullName>
            </value>
            <value>
                <fullName>Cleaning Services,204</fullName>
            </value>
            <value>
                <fullName>Cobbler,101</fullName>
            </value>
            <value>
                <fullName>Communications,206</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Category_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Category_of_Loan__c</fullName>
    <label>Category of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture,18</fullName>
            </value>
            <value>
                <fullName>Agricultural Equipment,96</fullName>
            </value>
            <value>
                <fullName>Agricultural Infrastructure,85</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Date_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Date_Disbursed__c</fullName>
    <label>Date Disbursed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Kiva_ID__c.field-meta.xml
<CustomField>
    <fullName>Kiva_ID__c</fullName>
    <label>Kiva ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Loan_Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Date__c</fullName>
    <label>Loan Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status__c</fullName>
    <label>Loan Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Application</fullName>
                <default>true</default>
                <label>New Application</label>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Main_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Main_Applicant_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Applicant Name</label>
    <referenceTo>Kiva_Client__c</referenceTo>
    <relationshipLabel>Kiva Loans</relationshipLabel>
    <relationshipName>Kiva_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Profile_Photo_Public_URL__c.field-meta.xml
<CustomField>
    <fullName>Profile_Photo_Public_URL__c</fullName>
    <label>Profile Photo (Public) URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Clothing</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Arts</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Personal Use</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kiva_Loan__c/recordTypes/Mozambique.recordType-meta.xml
<RecordType>
    <fullName>Mozambique</fullName>
    <active>true</active>
    <description>For Kiva Loan from Mozambique only</description>
    <label>Mozambique</label>
</RecordType>

force-app/main/default/objects/Kiva_Loan_Participation__c/Kiva_Loan_Participation__c.object-meta.xml
<CustomObject>
    <label>Kiva Loan Participation</label>
    <nameField>
        <displayFormat>KLP-{0000000}</displayFormat>
        <label>Kiva Loan Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kiva Loan Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kiva_Loan_Participation__c/fields/Category_of_loan__c.field-meta.xml
<CustomField>
    <fullName>Category_of_loan__c</fullName>
    <label>Category of loan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>18, Agricultural</fullName>
            </value>
            <value>
                <fullName>85, Agricultural Infrastructure</fullName>
            </value>
            <value>
                <fullName>96, Agricultural Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kiva_Loan_Participation__c/fields/Client_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_First_Name__c</fullName>
    <formula>Kiva_Client__r.Client_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan_Participation__c/fields/Client_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Last_Name__c</fullName>
    <formula>Kiva_Client__r.Client_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan_Participation__c/fields/Client_Phone__c.field-meta.xml
<CustomField>
    <fullName>Client_Phone__c</fullName>
    <formula>Kiva_Client__r.Client_Phone__c</formula>
    <label>Client Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan_Participation__c/fields/Kiva_Client__c.field-meta.xml
<CustomField>
    <fullName>Kiva_Client__c</fullName>
    <label>Kiva Client</label>
    <referenceTo>Kiva_Client__c</referenceTo>
    <relationshipLabel>Kiva Loan Participations</relationshipLabel>
    <relationshipName>Kiva_Loan_Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan_Participation__c/fields/Kiva_Loan__c.field-meta.xml
<CustomField>
    <fullName>Kiva_Loan__c</fullName>
    <label>Kiva Loan</label>
    <referenceTo>Kiva_Loan__c</referenceTo>
    <relationshipLabel>Kiva Loan Participations</relationshipLabel>
    <relationshipName>Kiva_Loan_Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan_Participation__c/fields/Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status__c</fullName>
    <formula>CASE(TEXT( Kiva_Loan__r.Kiva_Status__c), 
&quot;Refunded&quot;, &quot;Closed&quot;, 
&quot;Inactive&quot;, &quot;Closed&quot;,
&quot;Ended&quot;, &quot;Closed&quot;,
&quot;Defaulted&quot;, &quot;Defaulted&quot;,
&quot;Expired&quot;, &quot;Closed&quot;,
&quot;Active&quot;
)</formula>
    <inlineHelpText>Based on &quot;Kiva Status&quot; Field on the Kiva Loan record</inlineHelpText>
    <label>Loan Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kiva_Loan_Participation__c/recordTypes/Mozambique.recordType-meta.xml
<RecordType>
    <fullName>Mozambique</fullName>
    <active>true</active>
    <description>for Mozambique Kiva Loans</description>
    <label>Mozambique</label>
</RecordType>

force-app/main/default/objects/Kiva_Transaction__c/Kiva_Transaction__c.object-meta.xml
<CustomObject>
    <label>Kiva Transaction</label>
    <nameField>
        <displayFormat>KLT-{00000000}</displayFormat>
        <label>Kiva Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kiva Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kiva_Transaction__c/fields/Kiva_Loan__c.field-meta.xml
<CustomField>
    <fullName>Kiva_Loan__c</fullName>
    <label>Kiva Loan</label>
    <referenceTo>Kiva_Loan__c</referenceTo>
    <relationshipLabel>Kiva Transactions</relationshipLabel>
    <relationshipName>Kiva_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/KivaTest.cls
/************************************************************
|Author					|       Date        |    Comments
|************************************************************
|Aidar Assylbekov		|    12/22/2021     |    Created setup() method
|Gordon Lau				|    12/23/2021     |    Created testPOSTLoanDraft(), testPOSTRepayment() , testPOSTJournals() method
|Aidar Assylbekov		|    01/14/2022     |    Created testGETLoans() 
|Gordon Lau				|    01/25/2022     |    Modified class to test invocable methods
*/

@isTest
public class KivaTest {
    
    private static Kiva_Loan__c testKivaLoan;
    private static Kiva_Journal__c testKivaJournal;
    
    
    private static void setup()
    {
        system.debug('======== setup begins ========');
        // ********** CREATE TEST RECORDS IN RUNTIME ********
        // Creating Test Kiva Client A
        Kiva_Client__c testKivaClientA = new Kiva_Client__c (
            Client_First_Name__c = 'Test Client A First Name',
            Client_Last_Name__c = 'Test Client A Last Name',
            Client_Phone__c = '1234567890',
            Gender__c = 'Female'
        );
        insert testKivaClientA;
        
        // Creating Test Kiva Client B
        Kiva_Client__c testKivaClientB = new Kiva_Client__c (
            Client_First_Name__c = 'Test Client B First Name',
            Client_Last_Name__c = 'Test Client B Last Name',
            Client_Phone__c = '0987654321',
            Gender__c = 'Male'
        );
        insert testKivaClientB;
        
        // Creating Test Kiva Loan
        Id MozambiqueKivaLoanRecordType = Schema.SObjectType.Kiva_Loan__c.getRecordTypeInfosByName()
            .get('Mozambique').getRecordTypeId();
        
        KivaTest.testKivaLoan = new Kiva_Loan__c (
            Main_Applicant_Name__c = testKivaClientA.id,
            Kiva_ID__c = 'KIVA123',
            Loan_Type__c = 'Group',
            Loan_Status__c = 'Approved',
            Category_of_Loan__c = 'Agricultural Equipment,96',
            Sector__c = 'Agriculture',
            Activity__c = 'Agriculture,120',
            Profile_Photo_Public_URL__c = 'https://upload.wikimedia.org/wikipedia/commons/5/5a/John_Doe%2C_born_John_Nommensen_Duchac.jpg',
            Loan_Application_Date__c = date.newInstance(2021, 12, 13),
            Date_Disbursed__c = DateTime.newInstance(2021, 12, 1, 7, 8, 16),
            Loan_Description_for_KIVA__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            description_language_id__c = 'English',
            Loan_Group_Name__c = 'Test Group Name',
            RecordTypeId = MozambiqueKivaLoanRecordType
        );
        insert testKivaLoan;
        
        // Creating Test Kiva Participation A
        Id MozambiqueKivaLoanParticipationRecordType = Schema.SObjectType.Kiva_Loan_Participation__c.getRecordTypeInfosByName()
            .get('Mozambique').getRecordTypeId();
        
        Kiva_Loan_Participation__c testKivaLoanParticipationA = new Kiva_Loan_Participation__c (
            Kiva_Client__c = testKivaClientA.id,
            Kiva_Loan__c = testKivaLoan.id,
            Loan_amount_final__c = 20000,
            Loan_Amount_needed__c = 20000,
            RecordTypeId = MozambiqueKivaLoanParticipationRecordType
        );
        insert testKivaLoanParticipationA;
        
        // Creating Test Kiva Participation B         
        Kiva_Loan_Participation__c testKivaLoanParticipationB = new Kiva_Loan_Participation__c (
            Kiva_Client__c = testKivaClientB.id,
            Kiva_Loan__c = testKivaLoan.id,
            Loan_amount_final__c = 40000,
            Loan_Amount_needed__c = 40000,
            RecordTypeId = MozambiqueKivaLoanParticipationRecordType
        );
        insert testKivaLoanParticipationB;
        
        // Kiva Transaction Record Type Invoice
        Id InvoiceKivaTransactionRecordType = Schema.SObjectType.Kiva_Transaction__c.getRecordTypeInfosByName()
            .get('Kiva Invoice').getRecordTypeId();
        
        // Creating Test Kiva Transaction First Invoice
        Kiva_Transaction__c testKivaTransactionFirstInvoice = new Kiva_Transaction__c (
            Kiva_Loan__c = testKivaLoan.id,
            Date_due__c = date.newInstance(2022, 1, 1),
            Total_of_scheduled_Payments__c = 3,
            Payment_Order__c = 1,
            Admin_fee_for_Payment__c = 2000,
            Kiva_Payment_due__c = 20000,
            RecordTypeId = InvoiceKivaTransactionRecordType
        );
        insert testKivaTransactionFirstInvoice;
        
        // Creating Test Kiva Transaction Second Invoice
        Kiva_Transaction__c testKivaTransactionSecondInvoice = new Kiva_Transaction__c (
            Kiva_Loan__c = testKivaLoan.id,
            Date_due__c = date.newInstance(2022, 2, 1),
            Total_of_scheduled_Payments__c = 3,
            Payment_Order__c = 2,
            Admin_fee_for_Payment__c = 2000,
            Kiva_Payment_due__c = 20000,
            RecordTypeId = InvoiceKivaTransactionRecordType
        );
        insert testKivaTransactionSecondInvoice;
        
        // Creating Test Kiva Transaction Third Invoice
        Kiva_Transaction__c testKivaTransactionThirdInvoice = new Kiva_Transaction__c (
            Kiva_Loan__c = testKivaLoan.id,
            Date_due__c = date.newInstance(2022, 3, 1),
            Total_of_scheduled_Payments__c = 3,
            Payment_Order__c = 3,
            Admin_fee_for_Payment__c = 2000,
            Kiva_Payment_due__c = 20000,
            RecordTypeId = InvoiceKivaTransactionRecordType
        );
        insert testKivaTransactionThirdInvoice;
        
        // Creating Test Kiva Transaction Type Payment In
        Id PaymentInKivaTransactionRecordType = Schema.SObjectType.Kiva_Transaction__c.getRecordTypeInfosByName()
            .get('Kiva Payment In').getRecordTypeId();
        
        Kiva_Transaction__c testKivaTransactionPaymentIn = new Kiva_Transaction__c (
            Kiva_Loan__c = testKivaLoan.id,
            Payment_received_date__c = date.newInstance(2022, 2, 8),
            Payment_received__c = 2222,
            RecordTypeId = PaymentInKivaTransactionRecordType
        );
        insert testKivaTransactionPaymentIn;
        
        // Creating Test Kiva Journal
        KivaTest.testKivaJournal = new Kiva_Journal__c (
            Kiva_Loan__c = testKivaLoan.id,
            Date_of_Entry__c = date.newInstance(2021, 12, 21),
            Final_Body_Text__c = 'Test Final Body Text',
            Subject__c = 'Test Subject',
            URL_for_Attached_Image__c = 'https://i.kym-cdn.com/entries/icons/facebook/000/005/608/nyan-cat-01-625x450.jpg'        
        );
        insert testKivaJournal;
        
        system.debug('======== setup end ========');        
        // ************* Call METHODS to execute tests
    }
    
    static testMethod void testPOSTLoanDraft() {
        Test.setMock(HttpCalloutMock.class, new KivaAPIMockTest());
        // calls the setup above to create dummy records in runtime
        KivaTest.setup();
        List<Id> TESTLoanDraftIds = new List<Id>();
        TESTLoanDraftIds.add(KivaTest.testKivaLoan.id);
        
        Test.startTest();
        // Make the calls!
        
        List<Id> TESTLoanIdsfromFLOW = new List<Id>();
        // IN the proper implemention this List will be done by querying the loans that are in Repayment status, and invoked by Flow.
        // For now, we manually add the IDs of the loan records.
        TESTLoanIdsfromFLOW.add(testKivaLoan.Id);
        //TESTLoanIdsfromFLOW.add('aAS010000004JW8GAM'); 
        String CLabelfromFLOW = 'Kiva Credentials Moz';
        KivaPostLoanDraft.InputResource ONEFlowInput = new KivaPostLoanDraft.InputResource();
        ONEFlowInput.CountryLabel = CLabelfromFLOW;
        ONEFlowInput.KivaLoanDrafts = TESTLoanIdsfromFLOW;
        
        List<KivaPostLoanDraft.InputResource> FLOWinputs = new List<KivaPostLoanDraft.InputResource>();
        FLOWinputs.add(ONEFlowInput);
        
        system.debug('=== Calling KivaPostLoanDraft ===');
        KivaPostLoanDraft.POST(FLOWinputs);
        system.debug('=== KivaPostLoanDraft FINISHED ===');
        
        Test.stopTest();
        
        
    }
    
    static testMethod void testPOSTRepayment() {
        Test.setMock(HttpCalloutMock.class, new KivaAPIMockTest());
        // calls the setup above to create dummy records in runtime
        KivaTest.setup();
        List<Id> TESTRepayingLoanIds = new List<Id>();
        TESTRepayingLoanIds.add(KivaTest.testKivaLoan.id);
        // Country Label
        String CountryLabel = 'Kiva Credentials Moz';
        
        KivaPostLoanRepayments.InputResource TestInputForPOSTRepayments = new KivaPostLoanRepayments.InputResource();
        TestInputForPOSTRepayments.RepayingKivaLoans = TESTRepayingLoanIds;
        TestInputForPOSTRepayments.CountryLabel = CountryLabel;
        List<KivaPostLoanRepayments.InputResource> FLOWinputs = new List<KivaPostLoanRepayments.InputResource>();
        FLOWinputs.add(TestInputForPOSTRepayments);
        
        Test.startTest();
        // Make the calls!
        system.debug('=== Calling KivaPostLoanRepayments ===');
        KivaPostLoanRepayments.POST(FLOWinputs);    
        system.debug('=== KivaPostLoanRepayments FINISHED ===');
        Test.stopTest();
    }
    
    static testMethod void testPOSTJournal() {
        Test.setMock(HttpCalloutMock.class, new KivaAPIMockTest());
        // calls the setup above to create dummy records in runtime
        KivaTest.setup();
        List<Id> TESTJournalIds = new List<Id>();
        TESTJournalIds.add(KivaTest.testKivaJournal.id);
        
        // Country Label
        String CountryLabel = 'Kiva Credentials Moz';
        
        KivaPostLoanJournals.InputResource TestInputForPOSTJournals = new KivaPostLoanJournals.InputResource();
        TestInputForPOSTJournals.JournalsForPosting = TESTJournalIds;
        TestInputForPOSTJournals.CountryLabel = CountryLabel;
        
        List<KivaPostLoanJournals.InputResource> FLOWinputs = new List<KivaPostLoanJournals.InputResource>();
        FLOWinputs.add(TestInputForPOSTJournals);
        
        
        Test.startTest();
        // Make the calls!
		system.debug('=== Calling KivaPostLoanJournals ===');
        KivaPostLoanJournals.POST(FLOWinputs);
		system.debug('=== KivaPostLoanJournals FINISHED ===');        
        Test.stopTest();
        
    }
    
    static testMethod void testGETLoans() {
        Test.setMock(HttpCalloutMock.class, new KivaAPIMockTest());
        // calls the setup above to create dummy records in runtime
        KivaTest.setup();
        
        String limitValue = '500';
        String offsetValue = '0';
        String statusValue = 'payingBack';
        String CountryLabel = 'Kiva Credentials Moz';
        String queryValue = '403';        

        // setup Input Resource for GET Loans as parameters
        KivaGetLoans.InputResource TestInputForGETLoans = new KivaGetLoans.InputResource();
        TestInputForGETLoans.limitValue = limitValue;
        TestInputForGETLoans.offsetValue = offsetValue;
        TestInputForGETLoans.statusValue = statusValue;
        TestInputForGETLoans.CountryLabel = CountryLabel;
        TestInputForGETLoans.queryValue = queryValue;
        List<KivaGetLoans.InputResource> FLOWinputs = new List<KivaGetLoans.InputResource>();
        FLOWinputs.add(TestInputForGETLoans);

        Test.startTest();
        // Make the calls!        
        system.debug('=== Calling KivaGetLoans ===');
        KivaGetLoans.GET(FLOWinputs);
        system.debug('=== KivaGetLoans FINISHED ===');    
        Test.stopTest();
        
    }
    
}